language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

services: 
  - rabbitmq
  - mongodb
  - elasticsearch

env:
    global:
      - JRUBY_OPTS=--debug
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=1
      - CIKL_MONGO_URI=mongodb://localhost/cikl_test
      - CIKL_ELASTICSEARCH_URI=http://localhost:9200/
      - CIKL_ELASTICSEARCH_INDEX=cikl_test
      - CIKL_RABBITMQ_URL=amqp://guest:guest@localhost/%2F

before_install:
  - travis_retry sudo apt-get update -qq
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.4.deb && sudo dpkg -i --force-confnew elasticsearch-1.2.4.deb
  - sudo service elasticsearch restart
  - travis_retry travis/ruby/before_install.sh

install: 
  - travis_retry travis/ruby/install.sh

script:
  - travis_retry travis/ruby/script.sh
