services: 
  - rabbitmq
  - mongodb
  - elasticsearch

matrix:
  include:
    - language: ruby
      rvm: 1.9.3
      env: TEST_SUITE=ruby
    - language: ruby
      rvm: 2.0.0
      env: TEST_SUITE=ruby
    - language: ruby
      rvm: 2.1.0
      env: TEST_SUITE=ruby

env:
    global:
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=1
      - CIKL_MONGO_URI=mongodb://localhost/cikl_test
      - CIKL_ELASTICSEARCH_URI=http://localhost:9200/
      - CIKL_ELASTICSEARCH_INDEX=cikl_test
      - CIKL_RABBITMQ_URL=amqp://guest:guest@localhost/%2F

before_install:
  - travis_retry sudo apt-get update -qq
  - travis_retry travis/$TEST_SUITE/before_install.sh

install: 
  - travis_retry travis/$TEST_SUITE/install.sh

script:
  - travis_retry travis/$TEST_SUITE/script.sh
