language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

services: 
  - rabbitmq
  - mongodb

env:
    global:
      - JRUBY_OPTS=--debug
      - TEST_CLUSTER_COMMAND=/tmp/elasticsearch-1.2.1/bin/elasticsearch
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=1

before_install:
  - travis_retry sudo apt-get update -qq
  - travis_retry curl -# https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.tar.gz | tar xz -C /tmp || true
  - travis_retry travis/ruby/before_install.sh

install: 
  - travis_retry travis/ruby/install.sh

script:
  - travis_retry travis/ruby/script.sh
