default: &default
  mongo_uri: mongodb://localhost/cikl
  elasticsearch_hosts: 
    - http://localhost:9200/
  elasticsearch_index: cikl

development:
  <<: *default
  mongo_uri: mongodb://localhost/cikl_dev
  elasticsearch_index: cikl_dev

test:
  <<: *default
  mongo_uri: mongodb://localhost/cikl_test
  elasticsearch_hosts: 
    - http://localhost:9250/
  elasticsearch_index: cikl_test

production:
  <<: *default
